/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrustScoreRouteImport } from './routes/_app/trust-score'
import { Route as AppTermsSummarizerRouteImport } from './routes/_app/terms-summarizer'
import { Route as AppReportingRouteImport } from './routes/_app/reporting'
import { Route as AppPrivacyAnalyzerRouteImport } from './routes/_app/privacy-analyzer'
import { Route as AppLoyaltyRouteImport } from './routes/_app/loyalty'
import { Route as AppFraudDetectionRouteImport } from './routes/_app/fraud-detection'
import { Route as AppExtensionRouteImport } from './routes/_app/extension'
import { Route as AppDataProcessingRouteImport } from './routes/_app/data-processing'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrustScoreRoute = AppTrustScoreRouteImport.update({
  id: '/trust-score',
  path: '/trust-score',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsSummarizerRoute = AppTermsSummarizerRouteImport.update({
  id: '/terms-summarizer',
  path: '/terms-summarizer',
  getParentRoute: () => AppRoute,
} as any)
const AppReportingRoute = AppReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyAnalyzerRoute = AppPrivacyAnalyzerRouteImport.update({
  id: '/privacy-analyzer',
  path: '/privacy-analyzer',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppFraudDetectionRoute = AppFraudDetectionRouteImport.update({
  id: '/fraud-detection',
  path: '/fraud-detection',
  getParentRoute: () => AppRoute,
} as any)
const AppExtensionRoute = AppExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => AppRoute,
} as any)
const AppDataProcessingRoute = AppDataProcessingRouteImport.update({
  id: '/data-processing',
  path: '/data-processing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-processing': typeof AppDataProcessingRoute
  '/extension': typeof AppExtensionRoute
  '/fraud-detection': typeof AppFraudDetectionRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/privacy-analyzer': typeof AppPrivacyAnalyzerRoute
  '/reporting': typeof AppReportingRoute
  '/terms-summarizer': typeof AppTermsSummarizerRoute
  '/trust-score': typeof AppTrustScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-processing': typeof AppDataProcessingRoute
  '/extension': typeof AppExtensionRoute
  '/fraud-detection': typeof AppFraudDetectionRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/privacy-analyzer': typeof AppPrivacyAnalyzerRoute
  '/reporting': typeof AppReportingRoute
  '/terms-summarizer': typeof AppTermsSummarizerRoute
  '/trust-score': typeof AppTrustScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/data-processing': typeof AppDataProcessingRoute
  '/_app/extension': typeof AppExtensionRoute
  '/_app/fraud-detection': typeof AppFraudDetectionRoute
  '/_app/loyalty': typeof AppLoyaltyRoute
  '/_app/privacy-analyzer': typeof AppPrivacyAnalyzerRoute
  '/_app/reporting': typeof AppReportingRoute
  '/_app/terms-summarizer': typeof AppTermsSummarizerRoute
  '/_app/trust-score': typeof AppTrustScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/data-processing'
    | '/extension'
    | '/fraud-detection'
    | '/loyalty'
    | '/privacy-analyzer'
    | '/reporting'
    | '/terms-summarizer'
    | '/trust-score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/data-processing'
    | '/extension'
    | '/fraud-detection'
    | '/loyalty'
    | '/privacy-analyzer'
    | '/reporting'
    | '/terms-summarizer'
    | '/trust-score'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/data-processing'
    | '/_app/extension'
    | '/_app/fraud-detection'
    | '/_app/loyalty'
    | '/_app/privacy-analyzer'
    | '/_app/reporting'
    | '/_app/terms-summarizer'
    | '/_app/trust-score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trust-score': {
      id: '/_app/trust-score'
      path: '/trust-score'
      fullPath: '/trust-score'
      preLoaderRoute: typeof AppTrustScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms-summarizer': {
      id: '/_app/terms-summarizer'
      path: '/terms-summarizer'
      fullPath: '/terms-summarizer'
      preLoaderRoute: typeof AppTermsSummarizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reporting': {
      id: '/_app/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof AppReportingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy-analyzer': {
      id: '/_app/privacy-analyzer'
      path: '/privacy-analyzer'
      fullPath: '/privacy-analyzer'
      preLoaderRoute: typeof AppPrivacyAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loyalty': {
      id: '/_app/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fraud-detection': {
      id: '/_app/fraud-detection'
      path: '/fraud-detection'
      fullPath: '/fraud-detection'
      preLoaderRoute: typeof AppFraudDetectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extension': {
      id: '/_app/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof AppExtensionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-processing': {
      id: '/_app/data-processing'
      path: '/data-processing'
      fullPath: '/data-processing'
      preLoaderRoute: typeof AppDataProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataProcessingRoute: typeof AppDataProcessingRoute
  AppExtensionRoute: typeof AppExtensionRoute
  AppFraudDetectionRoute: typeof AppFraudDetectionRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppPrivacyAnalyzerRoute: typeof AppPrivacyAnalyzerRoute
  AppReportingRoute: typeof AppReportingRoute
  AppTermsSummarizerRoute: typeof AppTermsSummarizerRoute
  AppTrustScoreRoute: typeof AppTrustScoreRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDataProcessingRoute: AppDataProcessingRoute,
  AppExtensionRoute: AppExtensionRoute,
  AppFraudDetectionRoute: AppFraudDetectionRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppPrivacyAnalyzerRoute: AppPrivacyAnalyzerRoute,
  AppReportingRoute: AppReportingRoute,
  AppTermsSummarizerRoute: AppTermsSummarizerRoute,
  AppTrustScoreRoute: AppTrustScoreRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
